server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/   # Update this to match your Eureka server URL
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
